CONFIG_CMD_FAT=y
CONFIG_BOOTM_NETBSD=y
CONFIG_BOARD_EARLY_INIT_F=y
CONFIG_CMD_ITEST=y
CONFIG_BOOTM_VXWORKS=y
CONFIG_MX28=y
CONFIG_SYS_PROMPT="=> "
CONFIG_CMD_EDITENV=y
CONFIG_CMD_MTDPARTS=y
CONFIG_CMD_SETEXPR=y
CONFIG_SYS_MAX_NAND_DEVICE=y
CONFIG_SYS_GBL_DATA_SIZE=128
CONFIG_VERSION_VARIABLE=y
CONFIG_CMD_CRC32=y
CONFIG_SYS_LONGHELP=y
CONFIG_SYS_NAND_5_ADDR_CYCLE=y
CONFIG_SYS_LOAD_ADDR=$(CONFIG_LOADADDR)
CONFIG_CMD_XIMG=y
CONFIG_CMD_CACHE=y
CONFIG_CMD_NAND_TRIMFFS=y
CONFIG_BOOTDELAY=y
CONFIG_SYS_NAND_BASE=0x60000000
CONFIG_SYS_HELP_CMD_WIDTH=8
CONFIG_NR_DRAM_BANKS=y
CONFIG_FS_FAT=y
CONFIG_RTC_MXS=y
CONFIG_BOOTM_RTEMS=y
CONFIG_SYS_CBSIZE=1024
CONFIG_CMD_UBI=y
CONFIG_ENV_RANGE="(512 * 1024)"
CONFIG_BOOTM_LINUX=y
CONFIG_CMD_CONSOLE=y
CONFIG_APBH_DMA=y
CONFIG_SYS_CPU="arm926ejs"
CONFIG_MII=y
CONFIG_FEC_MXC=y
CONFIG_MTD_PARTITIONS=y
CONFIG_CMD_MISC=y
CONFIG_PL011_CLOCK=24000000
CONFIG_SPL_LIBCOMMON_SUPPORT=y
CONFIG_ENV_OFFSET=0x300000
CONFIG_USB_MAX_CONTROLLER_COUNT=y
CONFIG_ENV_OVERWRITE=y
CONFIG_CMD_NET=y
CONFIG_ENV_SIZE="(16 * 1024)"
CONFIG_SPL_BUILD=y
CONFIG_SYS_MALLOC_LEN=0x00400000
CONFIG_SYS_TEXT_BASE=0x40000100
CONFIG_CMD_SAVEENV=y
CONFIG_ENV_SECT_SIZE="(128 * 1024)"
CONFIG_BOOTM_PLAN9=y
CONFIG_CMD_NAND=y
CONFIG_SPL_START_S_PATH="arch/arm/cpu/arm926ejs/mxs"
CONFIG_CMD_MEMORY=y
CONFIG_SYS_MAXARGS=32
CONFIG_PL011_SERIAL=y
CONFIG_CMD_RUN=y
CONFIG_SYS_PBSIZE="(CONFIG_SYS_CBSIZE + sizeof(CONFIG_SYS_PROMPT) + 16)"
CONFIG_FEC_XCV_TYPE="RMII"
CONFIG_BOARDDIR="board/freescale/mx28evk"
CONFIG_OF_LIBFDT=y
CONFIG_CMDLINE_EDITING=y
CONFIG_CMD_USB=y
CONFIG_ENV_OFFSET_REDUND="(CONFIG_ENV_OFFSET + CONFIG_ENV_RANGE)"
CONFIG_USB_EHCI=y
CONFIG_BOOTCOMMAND="mmc dev ${mmcdev}; if mmc rescan; then if run loadbootscript; then run bootscript; else if run loadimage; then run mmcboot; else run netboot; fi; fi; else run netboot; fi"
CONFIG_CMD_SETGETDCR=y
CONFIG_SYS_BOOT_RAMDISK_HIGH=y
CONFIG_SPL_GPIO_SUPPORT=y
CONFIG_ZLIB=y
CONFIG_LOADADDR=0x42000000
CONFIG_ETHPRIME="FEC0"
CONFIG_CMD_GO=y
CONFIG_CMD_BOOTD=y
CONFIG_CMD_BOOTM=y
CONFIG_CMD_BOOTZ=y
CONFIG_NET_MULTI=y
CONFIG_SYS_BARGSIZE=$(CONFIG_SYS_CBSIZE)
CONFIG_AUTO_COMPLETE=y
CONFIG_SYS_SOC="mxs"
CONFIG_SYS_HZ=1000
CONFIG_SPL_NO_CPU_SUPPORT_CODE=y
CONFIG_DOS_PARTITION=y
CONFIG_GZIP=y
CONFIG_MX28_FEC_MAC_IN_OCOTP=y
CONFIG_SYS_VENDOR="freescale"
CONFIG_USB_ETHER_SMSC95XX=y
CONFIG_CMD_FPGA=y
CONFIG_SYS_INIT_RAM_SIZE="(128 * 1024)"
CONFIG_SYS_BAUDRATE_TABLE="{ 9600, 19200, 38400, 57600, 115200 }"
CONFIG_SPL_LIBGENERIC_SUPPORT=y
CONFIG_SYS_HUSH_PARSER=y
CONFIG_SYS_SDRAM_BASE="PHYS_SDRAM_1"
CONFIG_ARCH_MISC_INIT=y
CONFIG_SPL_LDSCRIPT="arch/arm/cpu/arm926ejs/mxs/u-boot-spl.lds"
CONFIG_ENV_IS_IN_NAND=y
CONFIG_SYS_PROMPT_HUSH_PS2="> "
CONFIG_USB_ETHER_ASIX=y
CONFIG_CMD_ECHO=y
CONFIG_SYS_INIT_SP_OFFSET="(CONFIG_SYS_INIT_RAM_SIZE - GENERATED_GBL_DATA_SIZE)"
CONFIG_SYS_INIT_RAM_ADDR=0x00000000
CONFIG_SPL_PAD_TO=0
CONFIG_EXTRA_ENV_SETTINGS="ubifs_file=filesystem.ubifs\0update_nand_full_filename=u-boot.nand\0update_nand_firmware_filename=u-boot.sb\0update_nand_firmware_maxsz=0x100000\0update_nand_stride=0x40\0update_nand_count=0x4\0update_nand_get_fcb_size=nand device 0 ; nand info ; setexpr fcb_sz ${update_nand_stride} * ${update_nand_count};setexpr update_nand_fcb ${fcb_sz} * ${nand_writesize}\0update_nand_firmware_full=if tftp ${update_nand_full_filename} ; then run update_nand_get_fcb_size ; nand scrub -y 0x0 ${filesize} ; nand write.raw ${loadaddr} 0x0 ${fcb_sz} ; setexpr update_off ${loadaddr} + ${update_nand_fcb} ; setexpr update_sz ${filesize} - ${update_nand_fcb} ; nand write ${update_off} ${update_nand_fcb} ${update_sz} ; fi\0update_nand_firmware=if tftp ${update_nand_firmware_filename} ; then run update_nand_get_fcb_size ; setexpr fcb_sz ${update_nand_fcb} * 2 ; setexpr fw_sz ${update_nand_firmware_maxsz} * 2 ; setexpr fw_off ${fcb_sz} + ${update_nand_firmware_maxsz};nand erase ${fcb_sz} ${fw_sz} ; nand write ${loadaddr} ${fcb_sz} ${filesize} ; nand write ${loadaddr} ${fw_off} ${filesize} ; fi\0update_nand_kernel=mtdparts default; nand erase.part kernel; if test ${ip_dyn} = yes; then setenv get_cmd dhcp; else setenv get_cmd tftp; fi; ${get_cmd} ${image}; nand write ${loadaddr} kernel ${filesize}\0update_nand_fdt=mtdparts default; nand erase.part fdt; if test ${ip_dyn} = yes; then setenv get_cmd dhcp; else setenv get_cmd tftp; fi; ${get_cmd} ${fdt_file}; nand write ${loadaddr} fdt ${filesize}\0update_nand_filesystem=mtdparts default; nand erase.part filesystem; if test ${ip_dyn} = yes; then setenv get_cmd dhcp; else setenv get_cmd tftp; fi; ${get_cmd} ${ubifs_file}; ubi part filesystem; ubi create filesystem; ubi write ${loadaddr} filesystem ${filesize}\0nandargs=setenv bootargs console=${console_mainline},${baudrate} rootfstype=ubifs ubi.mtd=6 root=ubi0_0 ${mtdparts}\0nandboot=mtdparts default; run nandargs; nand read ${loadaddr} kernel 0x00400000; if test ${boot_fdt} = yes; then nand read ${fdt_addr} fdt 0x00080000; bootz ${loadaddr} - ${fdt_addr}; else if test ${boot_fdt} = no; then bootz; else echo \"ERROR: Set boot_fdt to yes or no.\"; fi; fi\0update_sd_firmware_filename=u-boot.sd\0update_sd_firmware=if mmc rescan ; then if tftp ${update_sd_firmware_filename} ; then setexpr fw_sz ${filesize} / 0x200 ; setexpr fw_sz ${fw_sz} + 1 ; mmc write ${loadaddr} 0x800 ${fw_sz} ; fi ; fi\0script=boot.scr\0image=zImage\0console_fsl=ttyAM0\0console_mainline=ttyAMA0\0fdt_file=imx28-evk.dtb\0fdt_addr=0x41000000\0boot_fdt=try\0ip_dyn=yes\0mmcdev=0\0mmcpart=2\0mmcroot=/dev/mmcblk0p3 rw rootwait\0mmcargs=setenv bootargs console=${console_mainline},${baudrate} root=${mmcroot}\0loadbootscript=fatload mmc ${mmcdev}:${mmcpart} ${loadaddr} ${script};\0bootscript=echo Running bootscript from mmc ...; source\0loadimage=fatload mmc ${mmcdev}:${mmcpart} ${loadaddr} ${image}\0loadfdt=fatload mmc ${mmcdev}:${mmcpart} ${fdt_addr} ${fdt_file}\0mmcboot=echo Booting from mmc ...; run mmcargs; if test ${boot_fdt} = yes || test ${boot_fdt} = try; then if run loadfdt; then bootz ${loadaddr} - ${fdt_addr}; else if test ${boot_fdt} = try; then bootz; else echo WARN: Cannot load the DT; fi; fi; else bootz; fi;\0netargs=setenv bootargs console=${console_mainline},${baudrate} root=/dev/nfs ip=dhcp nfsroot=${serverip}:${nfsroot},v3,tcp\0netboot=echo Booting from net ...; run netargs; if test ${ip_dyn} = yes; then setenv get_cmd dhcp; else setenv get_cmd tftp; fi; ${get_cmd} ${image}; if test ${boot_fdt} = yes; then if ${get_cmd} ${fdt_addr} ${fdt_file}; then bootz ${loadaddr} - ${fdt_addr}; else if test ${boot_fdt} = try; then bootz; else echo WARN: Cannot load the DT; fi;fi; else bootz; fi;\0"
CONFIG_BOOTFILE="uImage"
CONFIG_SYS_INIT_SP_ADDR="(CONFIG_SYS_INIT_RAM_ADDR + CONFIG_SYS_INIT_SP_OFFSET)"
CONFIG_SYS_ARCH="arm"
CONFIG_BAUDRATE=115200
CONFIG_SYS_BOARD="mx28evk"
CONFIG_CMDLINE_TAG=y
CONFIG_CMD_IMPORTENV=y
CONFIG_CMD_EXPORTENV=y
CONFIG_USB_HOST_ETHER=y
CONFIG_PARTITIONS=y
CONFIG_CMD_UBIFS=y
CONFIG_CMD_DATE=y
CONFIG_NAND_MXS=y
CONFIG_SYS_NO_FLASH=y
CONFIG_SYS_DEF_EEPROM_ADDR=0
CONFIG_SYS_MEMTEST_END=0x40400000
CONFIG_MACH_TYPE="MACH_TYPE_MX28EVK"
CONFIG_SPL=y
CONFIG_MTD_DEVICE=y
CONFIG_CMD_SOURCE=y
CONFIG_USB_STORAGE=y
CONFIG_USB_EHCI_MXS=y
CONFIG_DISPLAY_CPUINFO=y
CONFIG_EHCI_MXS_PORT1=y
CONFIG_SYS_REDUNDAND_ENVIRONMENT=y
CONFIG_SETUP_MEMORY_TAGS=y
CONFIG_SYS_MEMTEST_START=0x40000000
CONFIG_CMD_LOADB=y
CONFIG_CMD_LOADS=y
CONFIG_CMD_IMI=y
CONFIG_CONS_INDEX=0
CONFIG_LMB=y
CONFIG_ARM=y
CONFIG_RBTREE=y
CONFIG_CMD_GPIO=y
CONFIG_CMD_BDI=y
CONFIG_MXS_GPIO=y
CONFIG_LZO=y
CONFIG_EHCI_IS_TDI=y
CONFIG_BOOTSTAGE_USER_COUNT=20
CONFIG_ENV_SIZE_REDUND=$(CONFIG_ENV_SIZE)
CONFIG_CMD_MII=y
CONFIG_PL01x_PORTS="{ (void *)MXS_UARTDBG_BASE }"
